// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDD2wmjVVD3RIqQTvexlupsSGmRiXKItDw',
    appId: '1:23318055025:web:965afff6f8e67c9a57b3d0',
    messagingSenderId: '23318055025',
    projectId: 'chat-app-51d0a',
    authDomain: 'chat-app-51d0a.firebaseapp.com',
    storageBucket: 'chat-app-51d0a.appspot.com',
    measurementId: 'G-HCXHD00KCB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwTgujFuiXUtqgF2D4xA2twLiwGnw4DhI',
    appId: '1:23318055025:android:c6844a0116a700e857b3d0',
    messagingSenderId: '23318055025',
    projectId: 'chat-app-51d0a',
    storageBucket: 'chat-app-51d0a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6uoEWTKWTxCFvuT8nR2KCDTHJ5Cc4g-A',
    appId: '1:23318055025:ios:61bad34d3040acde57b3d0',
    messagingSenderId: '23318055025',
    projectId: 'chat-app-51d0a',
    storageBucket: 'chat-app-51d0a.appspot.com',
    iosBundleId: 'com.example.chat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC6uoEWTKWTxCFvuT8nR2KCDTHJ5Cc4g-A',
    appId: '1:23318055025:ios:61bad34d3040acde57b3d0',
    messagingSenderId: '23318055025',
    projectId: 'chat-app-51d0a',
    storageBucket: 'chat-app-51d0a.appspot.com',
    iosBundleId: 'com.example.chat',
  );
}
